---
# General variables
ansible_user: ubuntu
ansible_python_interpreter: /usr/bin/python3

# RPI-Ubuntu image related
boot_usercfg_txt_file: /boot/firmware/usercfg.txt
boot_cmdline_txt_file: /boot/firmware/cmdline.txt
boot_syscfg_txt_file: /boot/firmware/syscfg.txt

# I2C_setup
i2c_tools_apt_packages:
  - i2c-tools
  - libi2c-dev
  - python3-smbus
i2c_tools_dependencies_apt_pkgs:
  - python3-dev
  - python3-pip
  - python3-rpi.gpio
  - python3-setuptools
i2c_group: i2c
ssd1306_pip_pkgs:
  - adafruit-circuitpython-framebuf
  - adafruit-circuitpython-lis3dh
  - adafruit-circuitpython-ssd1306
  - Pillow
i2c_enable_lines: ["# Enable I2C", "dtparam=i2c_arm=on"]
i2c_increase_core_lines:
  - "# Increase I2C core to 1MHz"
  - "dtparam=i2c_baudrate=1000000"

# rpi_display
rpi_display_scripts_git_url: "https://raw.githubusercontent.com/faiyaz7283/rpi_display_scripts/master"
rpi_display_scripts: ["sys_status.py", "reset_display.py"]

# overclock_on, overclock_off
overclock_lines: ["# Overclock", "over_voltage=5", "arm_freq=2000"]

# docker_install, docker_remove
docker_gpg_id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
docker_apt_repo: "deb [arch=arm64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
docker_required_apt_pkgs:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
docker_apt_pkgs: ["docker-ce", "docker-ce-cli", "containerd.io"]
docker_lib_dir: /var/lib/docker

# docker_cgroup_setup, docker_cgroup_rollback
docker_daemon_json_file: /etc/docker/daemon.json
docker_cgroup_systemd_json_file:
    "exec-opts": ["native.cgroupdriver=systemd"]
    "log-driver": "json-file"
    "log-opts":
      "max-size": "100m"
    "storage-driver": "overlay2"
docker_systemd_service_dir: /etc/systemd/system/docker.service.d
docker_cgroup_limit_support_append: "cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1"

# raspi_config_install, raspi_config_remove
raspi_config_all_deb: "https://archive.raspberrypi.org/debian/pool/main/r/raspi-config/raspi-config_20200902_all.deb"

# jenkins_install, jenkins_remove
java_apt_pkgs: default-jre
jenkins_apt_pkgs: jenkins
jenkins_gpg_url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
jenkins_gpg_id: 62A9756BFD780C377CF24BA8FCEF32E745F2C3D5
jenkins_lts_apt_repo: "deb https://pkg.jenkins.io/debian-stable binary/" 

# k8s_install, k8s_remove
k8s_gpg_id: 54A647F9048D5688D7DA2ABE6A030B21BA07F4FB
k8s_gpg_url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
k8s_apt_repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
k8s_required_apt_pkgs: ["apt-transport-https", "curl"]
k8s_apt_pkgs: ["kubelet", "kubeadm", "kubectl"]
k8s_apt_remove_pkgs: "{{ k8s_apt_pkgs + ['kubernetes-cni', 'kube*'] }}"
k8s_required_modules: ["br_netfilter"]
k8s_sysctl_conf_file: /etc/sysctl.d/k8s.conf
k8s_sysctl_conf:
    "net.bridge.bridge-nf-call-ip6tables": "1"
    "net.bridge.bridge-nf-call-iptables": "1"
k8s_kube_dir: ~/.kube
