all:
  children:
    ctlr:
      hosts:
        localhost:
          ansible_connection: local
    cla:
      hosts:
        cla00:
        cla01:
        cla02:
        cla03:
        cla04:
        cla05:
        cla06:
        cla07:
      vars:
        ansible_user: ubuntu
    rpis:
      children:
        cla:
