---
- name: Install tools and dependencies to manage I2C
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg: "{{ i2c_tools_apt_packages + i2c_tools_dependencies_apt_pkgs }}"

- name: "Add user to {{ i2c_group }} group"
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: "{{ i2c_group }}"
    append: yes

- name: Install Python libraries for display device
  pip:
    name: "{{ ssd1306_pip_pkgs }}"

- name: "Check if I2C is enabled in {{ boot_syscfg_txt_file }}"
  become: yes
  lineinfile:
    path: "{{ boot_syscfg_txt_file }}"
    line: "{{ i2c_enable_lines[1] }}"
  check_mode: yes
  register: i2c_enable_result

- name: "If I2C is disable then enable in {{ boot_usercfg_txt_file }}"
  become: yes
  lineinfile:
    path: "{{ boot_usercfg_txt_file }}"
    line: "{{ item }}"
  loop: "{{ i2c_enable_lines }}"
  when: i2c_enable_result is changed
  register: i2c_enable
  
- name: "Increase I2c core to 1MHz in {{ boot_usercfg_txt_file }}"
  become: yes
  lineinfile:
    path: "{{ boot_usercfg_txt_file }}"
    line: "{{ item }}"
  loop: "{{ i2c_increase_core_lines }}"
  register: i2c_core_increase

- name: Reboot the system if config changes were made
  become: yes
  when: i2c_enable is changed or i2c_core_increase is changed
  reboot:

- name: Download scripts for I2C display devices
  get_url:
    url: "{{ rpi_display_scripts_git_url }}/{{ item }}"
    dest: "~/{{ item }}"
  loop: "{{ rpi_display_scripts }}"

