---
- name: Setting up docker engine
  hosts: "{{ target_hosts | default('cla') }}"

  tasks:
    - name: Install packages to allow apt to use a repository over HTTPS
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600
        pkg: "{{ docker_required_apt_pkgs }}"
        
    - name: Add docker GPG apt key
      become: yes
      apt_key:
        url: "{{ docker_gpg_url }}" 
        id: "{{ docker_gpg_id }}"

    - name: Add docker repository
      become: yes
      apt_repository:
        update_cache: yes
        repo: "{{ docker_apt_repo }}"
        
    - name: Install docker engine
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600
        pkg: "{{ docker_apt_pkgs }}"
