---
- name: Setting up docker engine
  become: yes
  hosts: cla

  vars:
    docker_gpg_id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
    docker_repo: "deb [arch=arm64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

  tasks:
    - name: Install packages to allow apt to use a repository over HTTPS
      apt:
        update_cache: yes
        cache_valid_time: 3600
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Add docker GPG apt key
      apt_key:
        url: "{{ docker_gpg_url }}" 
        id: "{{ docker_gpg_id }}"

    - name: Add docker repository
      apt_repository:
        update_cache: yes
        repo: "{{ docker_repo }}"

    - name: Install docker engine
      apt:
        update_cache: yes
        cache_valid_time: 3600
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
