---
- name: I2C setup
  hosts: cla

  vars:
    cla_user: ubuntu
    git_url: "https://raw.githubusercontent.com/faiyaz7283/rpi_display_scripts/master"

  tasks:
    - name: Install tools and dependencies to manage I2C
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600
        pkg:
          - i2c-tools
          - libi2c-dev
          - python3-dev
          - python3-pil
          - python3-pip
          - python3-rpi.gpio
          - python3-setuptools
          - python3-smbus

    - name: Add user to i2c group
      become: yes
      user:
        name: "{{ cla_user }}"
        groups: i2c
        append: yes

    - name: Install Python libraries for display device
      pip:
        name:
          - adafruit-circuitpython-framebuf
          - adafruit-circuitpython-lis3dh
          - adafruit-circuitpython-ssd1306

    - name: Check if I2C is enabled on syscfg txt file
      become: yes
      lineinfile:
        path: /boot/firmware/syscfg.txt
        line: "dtparam=i2c_arm=on"
      check_mode: yes
      register: i2c_enable_result

    - name: If I2C is disable then enable 
      become: yes
      lineinfile:
        path: /boot/firmware/usercfg.txt
        line: "{{ item }}"
      loop:
        - "# Enable I2C"
        - "dtparam=i2c_arm=on"
      when: i2c_enable_result is changed
      register: i2c_enable
      
    - name: Increase I2c core to 1MHz
      become: yes
      lineinfile:
        path: /boot/firmware/usercfg.txt
        line: "{{ item }}"
      loop:
        - "# Increase I2C core to 1MHz"
        - "dtparam=i2c_baudrate=1000000"
      register: i2c_core_increase

    - name: Reboot the system if config changes were made
      become: yes
      when: i2c_enable is changed or i2c_core_increase is changed
      reboot:

    - name: Download scripts for for I2C display devices
      get_url:
        url: "{{ git_url }}/{{ item }}"
        dest: "~/{{ item }}"
      loop:
        - sys_status.py
        - reset_display.py
