---
- name: Remove kubernetes
  hosts: "{{ target_hosts | default('cla') }}"
  
  tasks:
    - name: Kubeadm reset
      become: yes
      command: kubeadm reset -f
      ignore_errors: true
      
    - name: "Unhold {{ k8s_apt_pkgs | join(', ') }} apt packages from any system upgrades"
      become: yes
      dpkg_selections:
        name: "{{ item }}"
        selection: deinstall
      loop: "{{ k8s_apt_pkgs }}"

    - name: "Removing {{ k8s_apt_remove_pkgs | join(', ') }} apt packages"
      become: yes
      apt:
        state: absent
        purge: yes
        autoremove: yes
        pkg: "{{ k8s_apt_remove_pkgs }}"
      register: k8s_removed

    - name: Reboot
      become: yes
      when: k8s_removed is changed
      reboot:

    - name: "Remove directory {{ k8s_kube_dir }}"
      become: yes
      file:
        state: absent
        path: "{{ k8s_kube_dir }}"

    - name: Remove kubernetes repository
      become: yes
      apt_repository:
        state: absent
        repo: "{{ k8s_apt_repo }}"

    - name: Remove google GPG apt key
      become: yes
      apt_key:
        state: absent
        url: "{{ k8s_gpg_url }}" 
        id: "{{ k8s_gpg_id }}"
        
    - name: Rollback iptables bridged traffic setup
      become: yes
      ansible.posix.sysctl:
        state: absent
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        sysctl_file: "{{ k8s_sysctl_conf_file }}"
      loop: "{{ lookup('dict', k8s_sysctl_conf) }}"

    - name: "Remove the {{ k8s_sysctl_conf_file }} file"
      become: yes
      file:
        state: absent
        path: "{{ k8s_sysctl_conf_file }}"
      
    - name: "Disable {{ k8s_required_modules | join(', ') }} module(s)"
      become: yes
      community.general.modprobe:
        state: absent
        name: "{{ item }}"
      loop: "{{ k8s_required_modules }}"
