---
- name: Remove overclocking
  hosts: "{{ target_hosts | default('cla, ci') }}"
    
  tasks:
    - name: "Remove overclocking lines from {{ boot_usercfg_txt_file }}"
      become: yes
      lineinfile:
        state: absent
        path: "{{ boot_usercfg_txt_file }}"
        line: "{{ item }}"
      loop: "{{ overclock_lines }}"
      register: overclock_removed

    - name: Reboot to take effect
      become: yes
      when: overclock_removed is changed
      reboot:
