---
- name: Add overclocking
  hosts: "{{ target_hosts | default('cla, ci') }}"

  tasks:
    - name: "Add overclocking lines in {{ boot_usercfg_txt_file }}"
      become: yes
      lineinfile:
        path: "{{ boot_usercfg_txt_file }}"
        line: "{{ item }}"
      loop: "{{ overclock_lines }}"
      register: overclock_added
      
    - name: Reboot to take effect
      become: yes
      when: overclock_added is changed
      reboot:
