---
- name: Remove raspi-config
  hosts: "{{ target_hosts | default('debian') }}"

  tasks:
    - name: Remove raspi-config
      become: yes
      apt:
        state: absent
        autoremove: yes
        purge: yes
        name: raspi-config
