gpg_id: 54A647F9048D5688D7DA2ABE6A030B21BA07F4FB
gpg_url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
apt_repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
required_apt_pkgs: ["apt-transport-https", "curl"]
apt_pkgs: ["kubelet", "kubeadm", "kubectl"]
apt_remove_pkgs: "{{ apt_pkgs + ['kubernetes-cni', 'kube*'] }}"
required_modules: ["br_netfilter"]
sysctl_conf_file: /etc/sysctl.d/k8s.conf
sysctl_conf:
    "net.bridge.bridge-nf-call-ip6tables": "1"
    "net.bridge.bridge-nf-call-iptables": "1"
kube_dir: "{{ ansible_user_home }}/.kube"
cni_conf_dir: /etc/cni/net.d
network_cid: 10.244.0.0/16
cluster_init_txt: cluster_init.txt
cni_add_on_txt: cni_add_on.txt
worker_joined_txt: worker_joined.txt
flannel_dl: "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
