---
- name: Install packages to allow apt to use a repository over HTTPS
  become: yes
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 3600
    pkg: "{{ docker_required_apt_pkgs }}"
    
- name: Add docker GPG apt key
  become: yes
  apt_key:
    state: present
    url: "{{ docker_gpg_url }}" 
    id: "{{ docker_gpg_id }}"

- name: Add docker repository
  become: yes
  apt_repository:
    state: present
    update_cache: yes
    repo: "{{ docker_apt_repo }}"
    
- name: Install docker engine
  become: yes
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 3600
    pkg: "{{ docker_apt_pkgs }}"
