---
- name: Setup continous integration and development
  hosts: "{{ target_hosts | default('cicd') }}"
  
  tasks:
    - name: Docker
      import_role:
        name: docker_setup
      tags:
        - docker

    - name: Jenkins
      import_role:
        name: jenkins_install
      tags:
        - jenkins
    
    - name: Static analysis
      import_role:
        name: static_analysis_setup
      tags:
        - analysis

    - name: Testing framework
      import_role:
        name: testing_framework_setup
      tags:
        - testing
