---
- name: Authorized key
  hosts: "{{ target_hosts | default('cla') }}"

  tasks:
    - name: "Add authorized key"
      lineinfile:
        path: "{{ auth_keys_file | default('~/.ssh/authorized_keys') }}"
        line: "{{ authorized_key }}"
      tags:
        - add
        
    - name: "Remove authorized key"
      lineinfile:
        state: absent
        path: "{{ auth_keys_file | default('~/.ssh/authorized_keys') }}"
        line: "{{ authorized_key }}"
      tags:
        - rm
        - never
