---
- name: Install Jenkins server
  hosts: "{{ target_hosts | default('ci') }}"

  roles:
    - role: jenkins_install
      tags:
        - inst

    - role: jenkins_remove
      tags:
        - rm
        - never
