---
- name: Shutdown
  hosts: "{{ target_hosts | default('all') }}"
  
  tasks:
    - name: System shutdown
      become: yes
      shell: sleep 2 && /sbin/shutdown -c && /sbin/shutdown -h now
      async: 1
      poll: 0
